version: 4.27.0
markdownExploder: true
language:
  default: en
  hitlMode: adaptive
  fallbackToEnglish: true
  supportedLanguages:
    - en  # English
    - es  # Spanish
    - pt  # Portuguese
    - fr  # French
    - de  # German
    - it  # Italian
    - zh-cn  # Chinese Simplified
    - ja  # Japanese
    - ko  # Korean
    - ru  # Russian
    - ar  # Arabic
  agentNames:
    analyst:
      en: Mary
      es: María
      pt: Maria
      fr: Marie
      de: Maria
      it: Maria
      zh-cn: 美丽
      ja: 美里
      ko: 마리아
      ru: Мария
      ar: مريم
    architect:
      en: Winston
      es: Víctor
      pt: Victor
      fr: Victor
      de: Viktor
      it: Vittorio
      zh-cn: 伟强
      ja: 勝
      ko: 승현
      ru: Виктор
      ar: وليد
    dev:
      en: James
      es: Diego
      pt: João
      fr: Antoine
      de: Stefan
      it: Marco
      zh-cn: 建华
      ja: 拓海
      ko: 준호
      ru: Дмитрий
      ar: أحمد
    pm:
      en: John
      es: Carlos
      pt: Pedro
      fr: Pierre
      de: Hans
      it: Giovanni
      zh-cn: 志强
      ja: 健太
      ko: 민수
      ru: Иван
      ar: كريم
    po:
      en: Sarah
      es: Ana
      pt: Ana
      fr: Sophie
      de: Anna
      it: Anna
      zh-cn: 安娜
      ja: 恵美
      ko: 수연
      ru: Анна
      ar: سارة
    qa:
      en: Quinn
      es: Alex
      pt: Alex
      fr: Alex
      de: Alex
      it: Alex
      zh-cn: 志杰
      ja: 翔太
      ko: 현우
      ru: Алекс
      ar: عماد
    sm:
      en: Bob
      es: Roberto
      pt: Roberto
      fr: Robert
      de: Robert
      it: Roberto
      zh-cn: 博文
      ja: 博
      ko: 성민
      ru: Роберт
      ar: روبرت
    ux-expert:
      en: Sally
      es: Sofía
      pt: Sofia
      fr: Camille
      de: Sophie
      it: Sofia
      zh-cn: 思雅
      ja: 美咲
      ko: 지은
      ru: София
      ar: صوفيا
    github-pm:
      en: GitHubPM
      es: GitHubPM
      pt: GitHubPM
      fr: GitHubPM
      de: GitHubPM
      it: GitHubPM
      zh-cn: GitHubPM
      ja: GitHubPM
      ko: GitHubPM
      ru: GitHubPM
      ar: GitHubPM
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
workflow:
  planFile: docs/workflow-plan.md
  trackProgress: true
  enforceSequence: false
  updateOnCompletion: true
github:
  enabled: true
  apiToken: null  # Set via GITHUB_TOKEN environment variable
  repository: "gugamistri/AI-SQUAD"
  projectId: "1"
  organization: null
  kanbanColumns:
    noStatus: "No Status"
    humanReview: "Human Review"
    todo: "Todo"
    inProgress: "In Progress"
    done: "Done"
  syncOptions:
    autoCreateIssues: true
    autoUpdateStatus: true
    bidirectionalSync: true
    syncInterval: 300
  issueMapping:
    story: "user-story"
    epic: "epic"
    task: "task"
    bug: "bug"
  gitOperations:
    autoCommit: false
    autoPush: false
    createPR: false
    branchNaming: "ai-squad/{story-id}"
    commitMessage: "feat: {story-title} - AI-SQUAD generated"
